# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'checkNewCode.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_checkNewCode(object):
    def setupUi(self, checkNewCode):
        checkNewCode.setObjectName("checkNewCode")
        checkNewCode.resize(1033, 736)
        checkNewCode.setFocusPolicy(QtCore.Qt.NoFocus)
        checkNewCode.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.verticalLayout = QtWidgets.QVBoxLayout(checkNewCode)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(checkNewCode)
        self.label_2.setMaximumSize(QtCore.QSize(1000, 16777215))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setTabletTracking(True)
        self.label_2.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_2.setTextFormat(QtCore.Qt.AutoText)
        self.label_2.setScaledContents(False)
        self.label_2.setWordWrap(True)
        self.label_2.setOpenExternalLinks(False)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label = QtWidgets.QLabel(checkNewCode)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setTextFormat(QtCore.Qt.PlainText)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.line_fkko = QtWidgets.QLineEdit(checkNewCode)
        self.line_fkko.setMinimumSize(QtCore.QSize(0, 50))
        self.line_fkko.setObjectName("line_fkko")
        self.verticalLayout.addWidget(self.line_fkko)
        self.label_3 = QtWidgets.QLabel(checkNewCode)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.line_title = QtWidgets.QLineEdit(checkNewCode)
        self.line_title.setMinimumSize(QtCore.QSize(0, 50))
        self.line_title.setObjectName("line_title")
        self.verticalLayout.addWidget(self.line_title)
        self.output_text = QtWidgets.QPlainTextEdit(checkNewCode)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.output_text.setFont(font)
        self.output_text.setObjectName("output_text")
        self.verticalLayout.addWidget(self.output_text)
        self.save_new_fkko = QtWidgets.QPushButton(checkNewCode)
        self.save_new_fkko.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.save_new_fkko.setFont(font)
        self.save_new_fkko.setObjectName("save_new_fkko")
        self.verticalLayout.addWidget(self.save_new_fkko)

        self.retranslateUi(checkNewCode)
        QtCore.QMetaObject.connectSlotsByName(checkNewCode)

    def retranslateUi(self, checkNewCode):
        _translate = QtCore.QCoreApplication.translate
        checkNewCode.setWindowTitle(_translate("checkNewCode", "Добавление нового кода фККО в базу данных"))
        self.label_2.setText(_translate("checkNewCode", "Это окно добавления нового кода ФККО. Для корректной работы с базой данных советуем использовать данных из новейших нормативных документов."))
        self.label.setText(_translate("checkNewCode", "Введите код ФККО:"))
        self.label_3.setText(_translate("checkNewCode", "Введите название ФККО:"))
        self.save_new_fkko.setText(_translate("checkNewCode", "Сохранить"))
